### PR TITLE
stylistic changes 

### PR DESCRIPTION
**Pull request by timofeji**
*added scripts file for javascript garbage
*normalized css colors for consistent coloring
*some styling for presentation

### CODE REVIEW

**Comment by geohot** [comment]
hmm do we need javascript? I like the rest

**Comment by geohot** [comment]
meh, little javascript okay

**Comment by geohot** [comment]
you have cTH address?

**Comment by geohot** [comment]
this is very beautiful now

**Comment by timofeji** [comment]
0x3A4B6f92FDBFfdea3136C5800bf959D8E2CbCF24

imo: 1 js file for small 1off things but don't allow it to get bloated with bullshit

**Pull request merged**
